from selenium.webdriver.common.by import By

class ContratanteLocators:
    NOMBRE = (By.ID, "titularName")
    APELLIDO_PATERNO = (By.ID, "titularPaternalSurname")
    APELLIDO_MATERNO = (By.ID, "titularMaternalSurname")
    RUT = (By.ID, "titularRut")
    FECHA_NAC = (By.ID, "titularBirthdate")
    GENERO = (By.ID, "titularGender")
    SISTEMA_PENSIONAL = (By.ID, "titularPensionSystem")
    REGION = (By.ID, "titularRegion")
    COMUNA = (By.ID, "titularCommune")
    DIRECCION = (By.ID, "titularAddress")
    ESTATURA = (By.ID, "titularHeight")
    PESO = (By.ID, "titularWeight")
    CORREO_PRINCIPAL = (By.ID, "titularEmail")
    CORREO_VALIDACION = (By.ID, "titularEmailValidation")
    TELEFONO = (By.ID, "titularPhone")
    TIPO_PAGO = (By.ID, "titularPaymentType")
    TIPO_CUENTA = (By.ID, "titularAccountType")
    BANCO = (By.ID, "titularBank")
    NUMERO_CUENTA = (By.ID, "titularBankAccountNumber")
    BOTON_AGREGAR_BENEFICIARIO = (By.XPATH, "//button[normalize-space()='agregar asegurado']")

class BeneficiarioLocators:
    # Beneficiario 1
    NOMBRE = (By.NAME, "beneficiaryName0")
    APELLIDO_PATERNO = (By.NAME, "beneficiaryPaternalSurname0")
    APELLIDO_MATERNO = (By.NAME, "beneficiaryMaternalSurname0")
    RUT = (By.NAME, "beneficiaryRut0")
    FECHA_NAC = (By.NAME, "beneficiaryBirthdate0")
    GENERO = (By.NAME, "beneficiaryGender0")
    RELACION = (By.NAME, "beneficiaryKinship0")
    SISTEMA_PENSIONAL = (By.NAME, "beneficiaryPensionSystem0")
    REGION = (By.NAME, "beneficiaryRegion0")
    COMUNA = (By.NAME, "beneficiaryCommune0")
    DIRECCION = (By.NAME, "beneficiaryAddress0")
    ESTATURA = (By.NAME, "beneficiaryHeight0")
    PESO = (By.NAME, "beneficiaryWeight0")
    # Beneficiario 2
    NOMBRE2 = (By.NAME, "beneficiaryName1")
    APELLIDO_PATERNO2 = (By.NAME, "beneficiaryPaternalSurname1")
    APELLIDO_MATERNO2 = (By.NAME, "beneficiaryMaternalSurname1")
    RUT2 = (By.NAME, "beneficiaryRut1")
    FECHA_NAC2 = (By.NAME, "beneficiaryBirthdate1")
    GENERO2 = (By.XPATH, "(//mat-radio-group[@name='beneficiaryGender1'])[2]//mat-radio-button[contains(., 'Femenino')]")
    RELACION2 = (By.NAME, "beneficiaryKinship1")
    SISTEMA_PENSIONAL2 = (By.NAME, "beneficiaryPensionSystem1")
    REGION2 = (By.NAME, "beneficiaryRegion1")
    COMUNA2 = (By.NAME, "beneficiaryCommune1")
    DIRECCION2 = (By.NAME, "beneficiaryAddress1")
    ESTATURA2 = (By.NAME, "beneficiaryHeight1")
    PESO2 = (By.NAME, "beneficiaryWeight1")

class PagoLocators:
    PASARELA_PAGO = (By.XPATH, "//img[contains(@src,'kushki') or contains(@alt,'Kushki')]")
    NUMERO_TARJETA = (By.ID, "cardNumber")
    NOMBRE_TARJETA = (By.ID, "cardHolderName")
    FECHA_VENCIMIENTO = (By.ID, "dueDate")
    CVV = (By.ID, "cvc")
    BOTON_PAGAR = (By.XPATH, '//*[@id="cdk-step-content-0-1"]/div/div[1]/integration-form/form/formly-form/formly-field/formly-group/formly-field[4]/kushki/subscription-tdc/custom-payment-box/div/mat-card/mat-card-content/form/div/button')
    MENSAJE_SUSCRIPCION = (By.XPATH, "//h4[normalize-space()='Suscripción solicitada']")
    BOTON_SIGUIENTE = (By.XPATH, "//button[normalize-space()='Siguiente paso']")