from selenium.webdriver.common.by import By

class ContratanteLocators:
    NOMBRE = (By.ID, "titularName")
    APELLIDO_PATERNO = (By.ID, "titularPaternalSurname")
    APELLIDO_MATERNO = (By.ID, "titularMaternalSurname")
    RUT = (By.ID, "titularRut")
    FECHA_NAC = (By.ID, "titularBirthdate")
    GENERO = (By.ID, "titularGender")
    SISTEMA_PENSIONAL = (By.ID, "titularPensionSystem")
    REGION = (By.ID, "titularRegion")
    COMUNA = (By.ID, "titularCommune")
    DIRECCION = (By.ID, "titularAddress")
    ESTATURA = (By.ID, "titularHeight")
    PESO = (By.ID, "titularWeight")
    CORREO_PRINCIPAL = (By.ID, "titularEmail")
    CORREO_VALIDACION = (By.ID, "titularEmailValidation")
    TELEFONO = (By.ID, "titularPhone")
    TIPO_PAGO = (By.ID, "titularPaymentType")
    TIPO_CUENTA = (By.ID, "titularAccountType")
    BANCO = (By.ID, "titularBank")
    NUMERO_CUENTA = (By.ID, "titularBankAccountNumber")
    BOTON_AGREGAR_BENEFICIARIO = (By.XPATH, "//button[normalize-space()='agregar asegurado']")
    # Localizador para el checkbox de términos y condiciones (Angular Material)
    TERMINOS = (By.CSS_SELECTOR, "mat-checkbox#AcceptTerms")
    DPS_TERMINOS = (By.CSS_SELECTOR, "mat-checkbox#dpsAcceptTerms")


class BeneficiarioLocators:
    # Beneficiario 1
    NOMBRE = (By.NAME, "beneficiaryName0")
    APELLIDO_PATERNO = (By.NAME, "beneficiaryPaternalSurname0")
    APELLIDO_MATERNO = (By.NAME, "beneficiaryMaternalSurname0")
    RUT = (By.NAME, "beneficiaryRut0")
    FECHA_NAC = (By.NAME, "beneficiaryBirthdate0")
    GENERO = (By.NAME, "beneficiaryGender0")
    RELACION = (By.NAME, "beneficiaryKinship0")
    SISTEMA_PENSIONAL = (By.NAME, "beneficiaryPensionSystem0")
    REGION = (By.NAME, "beneficiaryRegion0")
    COMUNA = (By.NAME, "beneficiaryCommune0")
    DIRECCION = (By.NAME, "beneficiaryAddress0")
    ESTATURA = (By.NAME, "beneficiaryHeight0")
    PESO = (By.NAME, "beneficiaryWeight0")
    # Beneficiario 2
    NOMBRE2 = (By.NAME, "beneficiaryName1")
    APELLIDO_PATERNO2 = (By.NAME, "beneficiaryPaternalSurname1")
    APELLIDO_MATERNO2 = (By.NAME, "beneficiaryMaternalSurname1")
    RUT2 = (By.NAME, "beneficiaryRut1")
    FECHA_NAC2 = (By.NAME, "beneficiaryBirthdate1")
    GENERO2 = (By.NAME, "beneficiaryGender1")
    RELACION2 = (By.NAME, "beneficiaryKinship1")
    SISTEMA_PENSIONAL2 = (By.NAME, "beneficiaryPensionSystem1")
    REGION2 = (By.NAME, "beneficiaryRegion1")
    COMUNA2 = (By.NAME, "beneficiaryCommune1")
    DIRECCION2 = (By.NAME, "beneficiaryAddress1")
    ESTATURA2 = (By.NAME, "beneficiaryHeight1")
    PESO2 = (By.NAME, "beneficiaryWeight1")

class dpsLocators:
    DPS_RADIO_1 = (By.NAME, "dps**q1")
    DPS_RADIO_2 = (By.NAME, "dps**q2")
    DPS_RADIO_3 = (By.NAME, "dps**q3")
    DPS_RADIO_4 = (By.NAME, "dps**q4")
    DPS_RADIO_5 = (By.NAME, "dps**q5")
    DPS_RADIO_6 = (By.NAME, "dps**q6")
    DPS_RADIO_7 = (By.NAME, "dps**q7")
    DPS_RADIO_8 = (By.NAME, "dps**q8")
    DPS_RADIO_9 = (By.NAME, "dps**q9")
    DPS_RADIO_10 = (By.NAME, "dps**q10")
    DPS_RADIO_11 = (By.NAME, "dps**q11")
    DPS_RADIO_12 = (By.NAME, "dps**q12")
    DPS_RADIO_13 = (By.NAME, "dps**q13")
    DPS_RADIO_14 = (By.NAME, "dps**q14")
    DPS_RADIO_15 = (By.NAME, "dps**q15")
    DPS_RADIO_16 = (By.NAME, "dps**q16")
    DPS_RADIO_17 = (By.NAME, "dps**q17")
    DPS_RADIO_18 = (By.NAME, "dps**q18")

class PagoLocators:
    PASARELA_PAGO = (By.XPATH, "//img[contains(@src,'kushki') or contains(@alt,'Kushki')]")
    NUMERO_TARJETA = (By.ID, "cardNumber")
    NOMBRE_TARJETA = (By.NAME, "HOLDER_NAME")
    FECHA_VENCIMIENTO = (By.ID, "expirationDate")
    CVV = (By.ID, "securityCode")
    BOTON_PAGAR = (By.XPATH, '//*[@id="cardPaymentBrick_container"]/form/div[3]/div/div/button')
    MENSAJE_SUSCRIPCION = (By.XPATH, "//h4[@class='alert-title']")
    BOTON_SIGUIENTE = (By.XPATH, "//button[normalize-space()='Siguiente paso']")

